[build]
builder = "dockerfile"
dockerfilePath = "server/Dockerfile"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
